[package]
name = "RustyXssDetector"
version = "0.1.0"
edition = "2021"
authors = ["Mo Ashouri <ashourics@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies.htmlstream]
version = "*"
